version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "80:80"
      - "9001-9012:9001-9012"
    environment:
      REDIS_URL: redis://redis:6379  # Redis URL for Docker
    depends_on:
      - redis
